project 'Restaurant-Guide-Swift-iOS.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Restaurant-Guide-Swift-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Restaurant-Guide-Swift-iOS
  # Material Design Components
  pod 'MaterialComponents/BottomNavigation'
  pod 'MaterialComponents/Banner'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Chips'
  pod 'MaterialComponents/NavigationDrawer'
  pod 'MaterialComponents/AppBar'

end
